# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
    param_fetcher_listener:  force
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations        
    allowed_methods_listener:  true
    serializer:
        serialize_null: true
    routing_loader:
        default_format: json
    view:
        view_response_listener:  true
        formats: { json: true, xml: false, rss: false }
        serialize_null: true
    exception:
        enabled: true
        codes:
            'App\Exception\MyException': 400
        messages:
            'App\Exception\MyException': true
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }